### ISSUE TITLE
Link for Pictures

### ISSUE THREAD

**Issue by hansnolte** [pelatx/brackets-link-file#1] opened 2017-01-22 15:04 UTC
Nice addition!
Is it possible to incorporate a "link file" for pictures?

**Comment by pelatx** [comment] 2017-01-23 15:06
Thank you.
I think there will be no problem to implement it.

**Comment by hansnolte** [comment] 2017-01-23 15:24
Great!!!
I'm looking forward.

Many thanks pelatx.

**Comment by pelatx** [comment] 2017-01-24 10:06
I have incorporated the changes you proposed. If you find any problem, please let me know.

Thanks for the idea.

**Comment by hansnolte** [comment] 2017-01-24 11:48
Hi pelatx,

it does not work.

I have created a blank HTML page.
Place the Cursor between the body tag.
Then save the page.
In the Project tree right click on the file -> LinkFile ... and nothing.
Absolutely nothing, no requester no error message.

Win 7 64Bit
Brackets Release 1.8 Build 1.8.0-17108

**Comment by pelatx** [comment] 2017-01-24 22:59
It works well for me. How have you updated the extension?

**Comment by hansnolte** [comment] 2017-01-25 09:55
Install from Url.

I use Brackets portable from here (Since several versions already).
https://github.com/sagiegurari/brackets-portable/releases/tag/v1.8.0.1

I have several Plug-Ins installed without ever having a problem.

I just done a fresh installation again.
Brackets LinkFile is the only plug-in.

And again... Absolut Nothing.

**Comment by pelatx** [comment] 2017-01-25 10:29
I have reproduced the steps that you comment, but on Windows 10, and it works for me.

What image format are you trying to link to?

**Comment by hansnolte** [comment] 2017-01-25 11:08
Png or Jpeg.

What exactly should happen.
Is there a requester?
Do I have to select anything?

**Comment by hansnolte** [comment] 2017-01-25 15:05
I have just installed the original Brackets (from http://brackets.io) in Win 10 (Virtualbox).
The same. No Requester or Error-Message... Nothing!

Something is missing!
Have you installed something else?

**Comment by pelatx** [comment] 2017-01-25 16:31
I do not imagine what is happening.

I have updated the extension in Brackets Extension Registry, removed that from my Brackets, installed from the Extension Manager, and no problem.

I leave you a video of my desktop with the whole process and linking a couple of images (png, jpg).
Same result in Win10 (Virtualbox) with Brackets Portable.

https://vimeo.com/201000723

**Comment by hansnolte** [comment] 2017-01-25 17:06
Oh No!!!

All files must be in the same folder.
 
I thought it comes a requester with which I can select a file somewhere on the hard drive. 

It works and it is a great time saver.

Thank you very much pelatx!!!


P.S. Put a link to the Vimeo video on your github page.

**Comment by pelatx** [comment] 2017-02-04 06:26
I have reopened this issue because I liked the idea of a requester, and copy the chosen file to the working directory at the same time it is linked.

I could not think how to implement it without losing the simplicity of the extension. But I think I already have it.

Thanks again for the idea.

**Comment by hansnolte** [comment] 2017-02-04 11:29
Hi pelatx, 
great idea to copy the files into the project folder.
You're right, it must be easy to use.

I'm looking forward to the new version!

**Comment by pelatx** [comment] 2017-02-15 23:40
I have posted a pre-release with the changes discussed in this issue. 
The file selection dialog is still rudimentary, but fully functional. The repository homepage explains everything necessary, with links to videos as well.

**Comment by hansnolte** [comment] 2017-02-16 10:05
Hi pelatx,
looks great.

A few problems.
I can only select the C: partition.
I'm not coming to D: or E:
![only-c-partition](https://cloud.githubusercontent.com/assets/7922627/23016702/b4d20802-f437-11e6-8435-615f162ccf99.jpg)



SVG's are not linked.

Can you add height and width for "Link-" images?

Many greetings
Hans

**Comment by pelatx** [comment] 2017-02-16 16:03
Hi

I completely forgot about other drives in Windows. I do not use it and I only have a virtual machine for testing.
In Linux there is no problem with this and I did not think about it. I'll try to fix it.

SVG file is recognized by the Brackets API as such, not as an image. Because the extension relies on the API, it has not been supported. I'll fix it soon.

At first the image tag had height and width. But I discarded it because they are not mandatory attributes. I do not know if they should be included.

Greetings.

**Comment by pelatx** [comment] 2017-02-17 10:15
New pre-release v1.2.0-alpha.1.

Better design and performance of the file selection dialog.
SVG image support.
Added height and width to image tag.

The problem of Windows volumes has a difficult solution due to several factors, related to the way the dialog is done and the lack of support for this in Brackets and Node.js (as far as I know).
The only reason I made this 'native Brackets' file selection dialog, is that the system dialog that Brackets exposes did not allow me to select multiple files, even if the corresponding flag was enabled.
I've solved this by reinventing the wheel, hehe. But it has its negative consequences (at least for now) like Windows unsupported volumes.

For now, from what I've seen, it's too complex to implement this. So the extension stays this way. But I'll keep investigating.

I will keep this pre-release a while before the final release, waiting for bugs to appear. Then I will push it to the extension registry and I think I could close this issue.

Thanks again for your good ideas and suggestions. I think thanks to them now this is a better extension. :-)

**Comment by hansnolte** [comment] 2017-02-17 12:15
Hi pelatx,

runs absolute smoothly.

Too bad the partition selection does not work.

I thought all the time to an old editor called Scriptly.
There, you could simply pull everything from anywhere.
[scriptly.zip](https://github.com/pelatx/brackets-link-file/files/783144/scriptly.zip)

This is already noticeable to me often, that Brackets in this direction is very limited.

Anyway.

Once again, thank you for this fantastic plugin.
Hans

**Comment by pelatx** [comment] 2017-02-27 17:22
New pre-release v1.2.0-beta.

Files selection dialog:
- Support for different volumes in Windows.
- Added navigation bar.

I close this issue because we are so far from "Link for pictures", hehe.

Anything else in a new one. Thanks Hans.

**Closed as completed by pelatx** 2017-02-27 17:22 UTC
Labels: enhancement

**Comment by hansnolte** [comment] 2017-02-28 08:44
Hi pelatx,

Perfekt!!!

Your add-on should be supplied as standard with Brackets.

Many thanks for your effort
 
Greetings
Hans
